#!/bin/bash
if [ -z "$1" ]; then
  echo "Please supply a name for the directory to hold the executables"
  exit
fi
if [ -f $1 ]; then
  echo "File $1 exist"
  exit
fi
if [ ! -d $1 ]; then
  cd "secp256k1" && ./autogen.sh
  ./configure --enable-experimental --enable-module-ecdh --with-bignum=no --enable-endomorphism
  make -j4
  cd ..
  mkdir $1
fi

echo Building debugging test
g++ tests/interface_test.cpp src/*.cpp bitcoin/*.cpp bitcoin/support/*.cpp bitcoin/crypto/*.cpp -g -Isecp256k1/include secp256k1/.libs/libsecp256k1.a  -lssl -lcrypto -lpthread -lboost_unit_test_framework -std=c++17 -o $1/interface_test
