#!/usr/bin/env bash
set -e

if [ "$#" -ne 1 ] || [ -z "$1" ]; then
  echo "Please supply the directory containing the test executables"
  exit 1
fi

test_dir=$1
if [ ! -d "$test_dir" ]; then
  echo "$test_dir is not a directory"
  exit 1
fi

tests=(
  spark_tests
  spark_name_tests
  address_tests
  ownership_tests
  spark_aead_tests
  spark_bpplus_tests
  spark_coin_tests
  spark_chaum_tests
  spark_encrypt_tests
  spark_f4grumble_tests
  spark_schnorr_tests
  spark_grootle_tests
  spark_mint_transaction_tests
  spark_spend_transaction_tests
  spark_transcript_tests
  full_test
)

for test in "${tests[@]}"; do
  echo "Running $test"
  "$test_dir/$test"
done
